[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "1b7695870c33d2103de0204ebf31109c6f579d5d"
os = "macos"

    [[Rmath.download]]
    sha256 = "5b3943c1bb3e79cdebe077d7f671fd5b9164048ac833285ad8f188f327267da0"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.aarch64-apple-darwin.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "c48517c0ffc6c42e79dc069fbceacee3326aae03"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "0a7d6e2b7ea7775712b416b74d487dc1bd6ff8293631d6c34587963e125398ae"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.aarch64-linux-gnu.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "6254a8cbd43eddb65476ce00550c5fdfb132b845"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "9093319416d00bb83b1ac9747c46b23eddd9d879d79807a7dccee9fd2f529a7c"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.aarch64-linux-musl.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "7e1a5f672b6e13140a13fe6521bcce23b211bafc"
os = "freebsd"

    [[Rmath.download]]
    sha256 = "6645e05b155c73a758a01d144fed11a6d824f58f004044e64ea3a29b202f0c62"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.aarch64-unknown-freebsd.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd97412d3e6f489495cb4a167f361ef8b102225c"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "5fc6ed194123f08f5763570c2b5c5b096d4fc6e5b90f49d9f2ad1a423f7053b4"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.armv6l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "04511e962a0c4b5d8096735899b0e696c651df69"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "8e197e42cb5f247c9e176e88a1686d84556d704224a9f1647e9f92f43b49b0b0"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.armv6l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d940ec86dd8a4306f62a06c587da21d6c621f9a6"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "ef7e755b9a8ebf3c33a471e1051126e82d8c43722d13d771d9bd1c8005f649b8"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.armv7l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8bb8327d0ce512d292b18db1df17bf25646b25f3"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "f6f94e184262642004d083048293513e95c0fc7cf4d7f6cb383c8f998a49fb1a"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.armv7l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "e8b8ec277f14d8ccf384c950c624b31286b19c2e"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "2a22619d00bf8e20187ee8df2b799a3cedd73bbf487c6d83d2920f43846ead6c"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.i686-linux-gnu.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "37b5db32e525642cf7ceeb929639898a1090f3a5"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "0d06d3a1309bd813a4c8bdcd12cef02f86865f0d40ae6701427e492b955d0673"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.i686-linux-musl.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "be8490208556f0c413a13c5c3b9a84a604cd0354"
os = "windows"

    [[Rmath.download]]
    sha256 = "03069beb4864e87ccbee1fbbb6ed4326434585a0c2510c71c8e1d761eeb85aea"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.i686-w64-mingw32.tar.gz"
[[Rmath]]
arch = "powerpc64le"
git-tree-sha1 = "44f1a3c38fe51110cf81737e8759d06373ca222e"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "693cea49d37bc809883eccc9e555e18ee5728335cb5fdbc7d13ac761b4a842ab"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.powerpc64le-linux-gnu.tar.gz"
[[Rmath]]
arch = "riscv64"
git-tree-sha1 = "6bbaff5bddbd14ea748b7455db611a3fc818e6b3"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "85c391d6ab67be633cbb38531375a434f7a23c407df556ee8e63335d1d90d634"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.riscv64-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "7b8fc91139105abbdddfc6bd21243b99e589558b"
os = "macos"

    [[Rmath.download]]
    sha256 = "a363e3731af0b5be0c264cd87db7f0cac4e83ac0c8169485cb4150a4a25312cf"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.x86_64-apple-darwin.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "32a70768bc7028e4079c6a4e04fcdcc721f12526"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "8b66be7d193a6f0b5af8575a88e1f753ebd6e697c49b3d3d1749a7d10d6e89f7"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.x86_64-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "e1656448e86ede72a433679beb644d823ecdd880"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "87d2432fe7c82b88b99a348b0b2d5992bbe9b02512b38701a36bb1ed17e5a2f9"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.x86_64-linux-musl.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "ee671f86f3ea63a6ce8caf7a261695627fe20ca5"
os = "freebsd"

    [[Rmath.download]]
    sha256 = "76300262d3eea3567a5ede57ce8b76b115477d7d3275834dc31f33a545ad19a1"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.x86_64-unknown-freebsd.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "d9ba205e5a16ced8fbf43cd4e63584142435dbd2"
os = "windows"

    [[Rmath.download]]
    sha256 = "f75dcc7d7ea1487aeb2ef4ccadb5091e30ab66b8789225f0eada3a927a8e2767"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.2+0/Rmath.v0.5.2.x86_64-w64-mingw32.tar.gz"
