[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "e8deade4dfcd48b56a7d2282b8ecfd950fe8fba1"
os = "macos"

    [[Rmath.download]]
    sha256 = "7a0a0242f1a69f30ee225fac26ac928c1074246dde2c146b5ad034cd9aab0099"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.aarch64-apple-darwin.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "7bf16e20743e93556b6953765c0f3c84a8062953"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "45a1cc86a2986fcddc52e3c3e2e158f7d0b13492926481ba2c2bed799fb71c8a"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.aarch64-linux-gnu.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "8b89324ff9181c58803859ce8959b031c0636826"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "83449ae675061fb92510a31618518ff600bbe37c7a7e42d2f5f2167ac4d825c8"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.aarch64-linux-musl.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf449b9d708af138fdde81deab0b6ea454cfbcbf"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "96bd3253b3561b6bbe91f14b5fea5ade3b7da75edf51c7d5d28d9baf1d9b2d20"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.armv6l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9eeb63411b8279d3cbbf031c649695af917ac7ec"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "50ea5867e31cea910851c653b32793be55d90942a74aec88768e307ad0054d97"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.armv6l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "89052926549c66e38ce5832f829a24f54797eb42"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "395a2afe538587a1cbed8edacdeb402bc4d86f3e57bfea6c3a1ab8da015104dc"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.armv7l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05b58af8cc4a62b3fb2ca52c3c4af1a3d6492e55"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "1b7e53c2005d5810c1cfcd4b0974f6299176f7333ba7602764393373d8d5e26b"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.armv7l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "5656b0fb56652813de385d9fc3d5639d00aabd6c"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "982dd3d0313a651abff6907a9e83ef4be5a246700917a9f36011b8b4fae6a9ec"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.i686-linux-gnu.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "b85a81353773013eb42689565af029594e28cd28"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "7c6b7f9a90e137e0bb7e83e0e521f65d24e22283eb1a2495a7ead2a93ac5716d"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.i686-linux-musl.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "4d38e2830eae290fc12949cbbc7d6e85571d6252"
os = "windows"

    [[Rmath.download]]
    sha256 = "d117202e68fbde6c7879c1dc012f3f8d2aab0032adddaac693190068101edb99"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.i686-w64-mingw32.tar.gz"
[[Rmath]]
arch = "powerpc64le"
git-tree-sha1 = "f6f672594707b5adf74c86ed980278fcd4f2e744"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "d99ef68f7f35d88654d97f19c867e7a780b5613ad411701d0f46a09df1f69838"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.powerpc64le-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "a31a5ded608cf90b404050bf4bec08fe0fafdee0"
os = "macos"

    [[Rmath.download]]
    sha256 = "c2f7e33dd14533f8c1894615aeca3e12b929b7ee5fe04c71376dd8041e62002a"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.x86_64-apple-darwin.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "bc8a1c15accaae9c10c1740fd377eed904ac6a5e"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "860980ad0a07dba4706fe32467b4996a6bd73d492a8b0ef4bea2c85078c41db3"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.x86_64-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "d5f98c2768f0dd8846bb5bf4c5cdcc4f2c416cb8"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "b24866a14579e93cdc11c8d256aa67492971e8f3ed143dff5b20f70ee9396d3d"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.x86_64-linux-musl.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "79a7a7a33e78a87f8e76b440c509b00545e9b256"
os = "freebsd"

    [[Rmath.download]]
    sha256 = "0ccdf340fe412cad029cbd7b564e9c4bc9fc1d4b2a9211520096c39e1907e948"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.x86_64-unknown-freebsd.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "6eefe0b81898a2049dc12b4d607e9f83b6b698e0"
os = "windows"

    [[Rmath.download]]
    sha256 = "09905347f85559a7b1ce61801adf708a3a98eebfc0ffbff65984221feb8e5bfc"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.3+0/Rmath.v0.4.3.x86_64-w64-mingw32.tar.gz"
