[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "e8b04484f6890b1740b828a0477bf0c3158865a7"
os = "macos"

    [[Rmath.download]]
    sha256 = "df8a52d14b4307dc1c3fb3cea09155452bce0f4e0ec35b7eb9d610aabec72643"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.aarch64-apple-darwin.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "a82c9cffe5949dd6b42222aac7afdc7d994e0921"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "ae26d9598f1d8cb1d4cdb105c49a999d830047c842eeb3a6d9e1dcb714a6be90"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.aarch64-linux-gnu.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "3e10e47756e3156ad85d8718850ce00f9818d007"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "136a1e99d6f0cdb08255ca175298169ab5831009f44066b7ce8b196972bb9bfb"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.aarch64-linux-musl.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2c359b1b5e071a6bbfcd5d41fe6d57f3eb3dece8"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "23595a40add0039936c328844b57415d12755228c1b52da3508241ca9fab4fa8"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ead38cc0857fa68d9e1d1664de79d72981de83ab"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "f013454824a8ac75eecb96bf3122d6298694df87e4d4f71814303ca67863d7c7"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.armv6l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa7c4c1833f1e34e452d3e2a3b3a332e0e0c1baf"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "30524d9e58ce66f949ca1977c226afb97598f793f4a0260ec06bcfc881448d84"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4182564973ec4f8c9f36ac3e36cfb4ff8116d4f"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "427ff4fdef9fe0be05da01f45c3d2b6b16203de9ae08ac85e2b464a3c73c53d2"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "e30a7161e39afefe9133f27e9d4ee92d4e0e3b54"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "40d9894f67508e5e99ab0e146d8bc4cb568648ae77fa11a066f58ef941175b24"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.i686-linux-gnu.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "1631522eca25cd12ac18062b83acb002aa3de1d3"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "20321e8ead40119bf6569b25728b1fb20e009424dbeed9950c6c032b3e5abdb0"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.i686-linux-musl.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "fab5faefd509ad894d5682e7c5ea85d914051e62"
os = "windows"

    [[Rmath.download]]
    sha256 = "819dd56c0ed66b51867b80e1bcf8066f8dfa30fa06bea973fe79db6bc9a1a5a3"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.i686-w64-mingw32.tar.gz"
[[Rmath]]
arch = "powerpc64le"
git-tree-sha1 = "8026c65f3e57d647ff8bb3d41651ec68e36388bc"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "cf2c6da636a8f3d35776f2e7bbc742608d31d6b72a7bb0eaff7e62f86bab7a1f"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "8e9cf80c49dc76c69d9f166656389413979a6b4a"
os = "macos"

    [[Rmath.download]]
    sha256 = "9ac68d3d0d15f8a2d439f8ff522ef2078051828b7e76a00e0e4ebb6e0ea17db5"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.x86_64-apple-darwin.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "9fbc41d22d1c5520455bd8e0f27fb304c5afe4ad"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "02228c96142cf31262eefd766075bcf34ffedc2fa27a8705d1f44b0521db27d9"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.x86_64-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "372e5dde13c0bd4512623cfd185f80334a4e3e2b"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "94ae2588f90806de5bd673d53a977be65b54d9e880d37a1233b459bb513cdfe8"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.x86_64-linux-musl.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "791cffb221c7491b6323b0f21265836d061a26d6"
os = "freebsd"

    [[Rmath.download]]
    sha256 = "ad18dbc63c622698e1d240b00afb511f971dc35c082e77945acd76ccac6ff58e"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "69231e845d921c19f7bb72e03d96f84b8e815e76"
os = "windows"

    [[Rmath.download]]
    sha256 = "db9b0528b3353fbbe8e59b6dacd7a01e3689be217a18c684c6721325590f67a7"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.5.0+0/Rmath.v0.5.0.x86_64-w64-mingw32.tar.gz"
